nameOverride: analytics-service
image:
  repository: ghcr.io/grvtech1/billfree-techops/analytics-service
  tag: "54c82e4d80bb87bd49ff6e073847fd8c41988130"
replicaCount: 2
containerPort: 8080
env:
  - name: SERVICE_NAME
    value: analytics-service
  - name: PORT
    value: "8080"
envFrom:
  - secretRef:
      name: billfree-app-secrets
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70



