nameOverride: analytics-service
image:
  repository: ghcr.io/grvtech1/billfree-techops/analytics-service
  tag: "b244860d6ae48e82f4126540087125fb4634ebd5"
replicaCount: 2
containerPort: 8080
env:
  - name: SERVICE_NAME
    value: analytics-service
  - name: PORT
    value: "8080"
envFrom:
  - secretRef:
      name: billfree-app-secrets
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
