nameOverride: analytics-service
image:
  repository: ghcr.io/grvtech1/billfree-techops/analytics-service
  tag: "283cb75a5b04e9096ec7300336e10476d4445a1c"
replicaCount: 2
containerPort: 8080
env:
  - name: SERVICE_NAME
    value: analytics-service
  - name: PORT
    value: "8080"
envFrom:
  - secretRef:
      name: billfree-app-secrets
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
